config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'static_pages/mission'

  get 'oauth/callback', to: 'oauths#callback' # for use with Github, Facebook
  get 'oauth/:provider', as: :auth_at_provider, to: 'oauths#oauth'
  post 'logout', as: :logout, to: 'oauths#destroy'

  resource :user, only: %i[show destroy] do
    resources :tasks do
      member do
        patch :pause
        patch :done
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  enum repeat_flag: { one_time: 0, repeat: 1 }
  enum pause_flag: { active: 0, pause: 1 }
  enum status: { todo: 0, done: 1 }

  validates :title, presence: true, length: { maximum: 50 }
  validates :tweet_content, presence: true, length: { maximum: 140 }
  validates :tweet_datetime, presence: true
  validates :repeat_tweet_time, presence: true, if: :repeat?
  validates :repeat_flag, presence: true
  validates :pause_flag, presence: true
  validates :status, presence: true
  validate :check_tweet_time
  validate :at_least_one_1, if: :repeat?

  scope :have_to_tweet, -> { todo.active.where(tweet_datetime: Time.current.ago(1.minute)..Time.current.since(5.minutes)) }

  def check_tweet_time
    if tweet_datetime&.past?
      errors.add(:tweet_datetime, 'は現在時刻より未来に設定してください')
    end
  end

  def at_least_one_1
    wdays = []
    wdays.push(
              tweet_sun,
              tweet_mon,
              tweet_tue,
              tweet_wed,
              tweet_thu,
              tweet_fri,
              tweet_sat
              )
    if wdays.all? { |wday| wday == 0 }
      errors.add(:repeat_flag, "は一つ以上の曜日を設定してください")
    end
  end

  # 次にツイートする曜日を取得
  def calc_next_tweet_wday(base_wday)
    tweet_wdays = [tweet_sun, tweet_mon, tweet_tue, tweet_wed, tweet_thu, tweet_fri, tweet_sat]
    next_tweet_wday = -1
    tweet_wdays.each_with_index do |wday, i|
      if i <= base_wday
        next
      end
      if wday == 1
        next_tweet_wday = i
        break
      end
    end
    if next_tweet_wday == -1
      tweet_wdays.each_with_index do |wday, j|
        if wday == 1
          next_tweet_wday = j
          break
        end
      end
    end
    next_tweet_wday
  end

  # 次にツイートする日時を取得
  def set_next_tweet_date(base_day)
    if one_time?
      return
    end
    wdays = %i[sunday monday tuesday wednesday thursday friday saturday]
    tweet_wdays = [
                   tweet_sun, tweet_mon, tweet_tue, tweet_wed, tweet_thu, tweet_fri, tweet_sat
                  ]
    tweet_time = repeat_tweet_time.to_s.split[1]
    today = Time.current.to_date.to_s
    today_tweet_datetime = (today + ' ' + tweet_time).in_time_zone
    base_day_string = base_day.to_date.to_s
    base_day_tweet_datetime = (base_day_string + ' ' + tweet_time).in_time_zone

    if tweet_wdays[base_day.wday] == 1 && Time.current < base_day_tweet_datetime
      self.tweet_datetime = today_tweet_datetime
    else
      next_tweet_wday = calc_next_tweet_wday(Time.current.wday)
      # 基準となる日からみて、次の〇曜日の日付を取得
      next_tweet_day = base_day.beginning_of_week(wdays[next_tweet_wday]).since(1.week).to_date.to_s
      self.tweet_datetime = (next_tweet_day + ' ' + tweet_time).in_time_zone
    end
  end

  def toggle_pause_flag!
    if active?
      pause!
    else
      active!
    end
  end

  def twitter_client
    access_token, access_token_secret = user.aes_decrypt
    @twitter_client ||= Twitter::REST::Client.new do |config|
      config.consumer_key        = Rails.application.credentials.twitter[:api_key]
      config.consumer_secret     = Rails.application.credentials.twitter[:api_secret_key]
      config.access_token        = access_token
      config.access_token_secret = access_token_secret
    end
  end

  def auto_tweet!
    begin
      twitter_client.update!(tweet_content)
    rescue StandardError => e
      logger.error e.backtrace.join("\n")
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)
    @task.set_next_tweet_date(Time.current)
    respond_to do |format|
      if @task.save
        format.js { flash.now[:success] = 'タスクを作成しました！' }
      else
        format.js { flash.now[:danger] = 'タスクを作成できませんでした' }
      end
    end
  end

  def edit; end

  def update
    @task = current_user.tasks.find(params[:id])
    set_tweet_time(@task)
    @task.assign_attributes(task_update_params)
    @task.set_next_tweet_date(Time.current)
    if @task.save
      if @task.one_time?
        render json: {repeat: false , tweet_datetime: @task.tweet_datetime.strftime('%Y-%m-%d %H:%M')}, status: :ok
      elsif @task.repeat?
        render json: {
                      repeat: true,
                      tweet_datetime: @task.tweet_datetime.strftime('%Y-%m-%d %H:%M'),
                      repeat_tweet_time: @task.repeat_tweet_time.strftime('%H:%M'),
                      wdays: [@task.tweet_sun, @task.tweet_mon, @task.tweet_tue, @task.tweet_wed,
                              @task.tweet_thu, @task.tweet_fri, @task.tweet_sat]
                      },
                      status: :ok
      end
    else
      render json: { task: @task, errors: { messages: @task.errors.full_messages } }, status: :bad_request
    end
  end

  def destroy
    @task = current_user.tasks.find(params[:id])
    respond_to do |format|
      @task.destroy!
      format.js { flash.now[:success] = 'タスクを削除しました' }
    end
  end

  def pause
    @task = current_user.tasks.find(params[:id])
    respond_to do |format|
      @task.toggle_pause_flag!
      if @task.pause?
        format.js { flash.now[:success] = 'タスクを休止しました！' }
      elsif @task.active?
        format.js { flash.now[:success] = 'タスクを再開しました！' }
      end
    end
  end

  def done
    @task = current_user.tasks.find(params[:id])
    respond_to do |format|
      @task.done!
      format.js { flash.now[:success] = 'タスクを完了しました！' }
    end
  end

  def task_params
    params.require(:task).permit(:title, :tweet_content, :repeat_flag, :tweet_datetime,
                                 :repeat_tweet_time, :tweet_sun, :tweet_mon,
                                 :tweet_tue, :tweet_wed, :tweet_thu, :tweet_fri,
                                 :tweet_sat, :user_id
                                )
  end

  def task_update_params
    params.require(:task).permit(:title, :tweet_content, :tweet_sun, :tweet_mon,
                                 :tweet_tue, :tweet_wed, :tweet_thu, :tweet_fri,
                                 :tweet_sat
                                )
  end

  # jQueryのAjaxメソッドでparamsを取得すると、年、月、日、時、分を個別で取得することになるため、TimeWithZoneクラスのオブジェクトを作成
  def set_tweet_time(task)
    if task.one_time?
      year = params.dig(:task, :tweet_year)
      month = params.dig(:task, :tweet_month)
      day = params.dig(:task, :tweet_day)
      hour = params.dig(:task, :tweet_hour)
      minute = params.dig(:task, :tweet_minute)
      time = Time.zone.parse("#{year}-#{month}-#{day} #{hour}:#{minute}:00")
      task.tweet_datetime = time
    elsif task.repeat?
      hour = params.dig(:task, :repeat_hour)
      minute = params.dig(:task, :repeat_minute)
      time = Time.zone.parse("#{hour}:#{minute}:00")
      task.repeat_tweet_time = time
    end
  end

end

app/views/tasks/_crud_menus.html.slim
ul.list-inline.justify-content-center id="js-taskCrudList-#{task.id}" style="float: right;"
  - if task.todo?
    li id="js-taskPause-#{task.id}" class="list-inline-item mr-3"
      - if task.active?
          = link_to pause_user_task_path(task.id), class: 'js-taskPause', remote: :true, method: :patch, data: { confirm: t('.confirm_pause_task') } do
            i.fas.fa-pause.font-awesome
      - elsif task.pause?
        = link_to pause_user_task_path(task.id), class: 'js-taskPause click-icon', remote: :true, method: :patch, data: { confirm: t('.confirm_active_task') } do
          i.far.fa-play-circle

    li.list-inline-item id="js-taskEdit-#{task.id}" class='click-icon mr-3'
      i.js-taskEdit.fas.fa-pencil-alt.font-awesome data-task-id='#{task.id}'

  li.list-inline-item.mr-3
    = link_to user_task_path(task.id), class: 'js-taskDelete click-icon', remote: :true, method: :delete, data: { confirm: t('.confirm_delete_task') } do
      i.fas.fa-trash-alt.font-awesome

app/views/tasks/_edit_form.html.slim
= form_with id:"js-taskEditForm-#{task.id}", class: 'taskEditForm', local: 'true' do |f|
  div id="js-errorMessage-#{task.id}"
    = render 'shared/error_message', errors: @errors
  - if task.one_time?
    .group-form.datetime-select
      = f.label Task.human_attribute_name(:tweet_datetime), class: 'mr-2 d-block label'
      = f.datetime_select id="js-editTweetDateTime-#{task.id}", { start_year: Time.current.year, end_year: Time.current.year.next,\
                                                                  default: task.tweet_datetime, minute_step: 30, date_separator: '/ ', datetime_separator: '- ', use_month_numbers: true }

  - if task.repeat?
    .group-form.datetime-select
      = f.label Task.human_attribute_name(:repeat_tweet_time), class: 'mr-2 label d-block'
      = f.time_select id="js-editTweetTime-#{task.id}", { default: task.repeat_tweet_time, minute_step: 30 }
    .form_group.my-3
      input type='checkbox' id="js-sun-#{task.id}" class='mr-1' name="editTweetWday-#{task.id}" value='sun'
      label for="js-sun-#{task.id}" = t('.sun')
      input type='checkbox' id="js-mon-#{task.id}" class='ml-4 mr-1' name="editTweetWday-#{task.id}" value='mon'
      label for="js-mon-#{task.id}" = t('.mon')
      input type='checkbox' id="js-tue-#{task.id}" class='ml-4 mr-1' name="editTweetWday-#{task.id}" value='tue'
      label for="js-tue-#{task.id}" = t('.tue')
      input type='checkbox' id="js-wed-#{task.id}" class='ml-4 mr-1' name="editTweetWday-#{task.id}" value='wed'
      label for="js-wed-#{task.id}" = t('.wed')
      input type='checkbox' id="js-thu-#{task.id}" class='ml-4 mr-1' name="editTweetWday-#{task.id}" value='thu'
      label for="js-thu-#{task.id}" = t('.thu')
      input type='checkbox' id="js-fri-#{task.id}" class='ml-4 mr-1' name="editTweetWday-#{task.id}" value='fri'
      label for="js-fri-#{task.id}" = t('.fri')
      input type='checkbox' id="js-sat-#{task.id}" class='ml-4 mr-1' name="editTweetWday-#{task.id}" value='sat'
      label for="js-sat-#{task.id}" = t('.sat')

  .form-group.mb-3
    = f.label Task.human_attribute_name(:title), class: 'mr-2 label'
    = f.text_field id="js-editTitle-#{task.id}", class: 'form-control', style:'display=block'

  .form-group
    = f.label Task.human_attribute_name(:tweet_content), class: 'mr-2 label'
    = f.text_area id="js-editTweetContent-#{task.id}", class:'form-control mb-1', style:'display:block', cols: '50', rows: '3'
  a.js-taskEditCancel.btn.btn-secondary.mr-2.py-1 data-task-id='#{task.id}' = t('.cancel')
  a.js-taskUpdate.btn.submit-task-btn.py-1[data-url='#{user_task_path(task.id)}'
    data-user-id='#{current_user.id}'
    data-task-id='#{task.id}'
    ]
    = t('.update')

app/views/tasks/_finish_btn.html.slim
- if task.todo?
  = link_to t('.finish_task'), done_user_task_path(task.id), remote: true, method: :patch, class: 'btn submit-task-btn my-3 py-1', data: { confirm: t('.confirm_finish_task') }
- if task.done?
  = t('.done')

app/views/tasks/_form.html.slim
.modal-dialog.modal-dialog-centered role="document"
  .modal-content
    .modal-header
      h5 class="modal-title"  = Task.model_name.human
      button type="button" class="close" data-dismiss="modal" aria-label="Close"
        span aria-hidden="true" &times;
    .modal-body
      = form_with model: [current_user, task], remote: true do |f|
        #js-errorMessage
        .form-group
          = f.label :title, class: 'col-form-label label'
          = f.text_field :title, class: 'form-control'
        .form-group#js-repeatFlag.mb-1
          = f.check_box :repeat_flag, { class: 'mr-2' }, 'repeat', 'one_time'
          = f.label :repeat_flag, class: 'label'

        .form-group#js-tweetDateTime.mb-2
          = f.label :tweet_datetime, class: 'col-form-label d-block label'
          = f.datetime_select :tweet_datetime, { start_year: Time.current.year, end_year: Time.current.year.next,\
                                                default: Time.current, minute_step: 30, date_separator: '/ ', datetime_separator: '- ', use_month_numbers: true }

        .form_group#js-wday.mb-2 style='display:none'
          .d-inline-block
            = f.check_box :tweet_sun, class: 'mr-1'
            = f.label :tweet_sun, t('.sun')
          .d-inline-block
            = f.check_box :tweet_mon, class: 'ml-4 mr-1'
            = f.label :tweet_mon, t('.mon')
          .d-inline-block
            = f.check_box :tweet_tue, class: 'ml-4 mr-1'
            = f.label :tweet_tue, t('.tue')
          .d-inline-block
            = f.check_box :tweet_wed, class: 'ml-4 mr-1'
            = f.label :tweet_wed, t('.wed')
          .d-inline-block
            = f.check_box :tweet_thu, class: 'ml-4 mr-1'
            = f.label :tweet_thu, t('.thu')
          .d-inline-block
            = f.check_box :tweet_fri, class: 'ml-4 mr-1'
            = f.label :tweet_fri, t('.fri')
          .d-inline-block
            = f.check_box :tweet_sat, class: 'ml-4 mr-1'
            = f.label :tweet_sat, t('.sat')

        .form-group#js-tweetTime style='display:none'
          = f.time_select :repeat_tweet_time, { minute_step: 30 }, class: 'mr-2'
          = f.label :repeat_tweet_time, class: 'label'
        .form-group
          = f.label :tweet_content, class: 'label'
          = f.text_area :tweet_content, cols: '50', rows: '3', class: 'form-control', placeholder: '140字以内'

        .modal-footer
          button type="button" class="btn btn-secondary" data-dismiss="modal" = t('.cancel')
          = f.button t('.submit'), class:'btn submit-task-btn'

app/views/tasks/_more_info_task.html.slim
div id="js-moreInfo-#{task.id}" class='more-info'
  i.fas.fa-angle-up.js-hideMoreInfo style='font-size:28px' data-task-id='#{task.id}'
  p.mb-0.label = Task.human_attribute_name(:tweet_content)
  div id="js-tweetContent-#{task.id}"
    = task.tweet_content

  .icon-menus.my-3
    div id="js-taskCrudMenus-#{task.id}"  class='d-inline-block'
      = render 'tasks/crud_menus', { user: task.user, task: task }

  div id="js-editTask-#{task.id}" class='mt-5'
    = render 'tasks/edit_form', task: task

i.fas.fa-angle-down.js-showMoreInfo style='font-size:28px' data-task-id='#{task.id}' id="js-hideIcon-#{task.id}"

app/views/tasks/_next_tweet_datetime.html.slim
- if task.one_time? 
  small.mr-4 = t('.tweet_datetime')
- if task.repeat?
  small.mr-4 = t('.next_tweet_datetime')
strong.repeat-time
  = task.tweet_datetime.strftime('%Y-%m-%d %H:%M')

app/views/tasks/_repeat_timing.html.slim
div id="js-repeatWdays-#{task.id}" class='d-inline-block'
  - if task.tweet_sun == 1
    span.sun.mr-2 = t('.sun')
  - if task.tweet_mon == 1
    span.mon.mr-2 = t('.mon')
  - if task.tweet_tue == 1
    span.tue.mr-2 = t('.tue')
  - if task.tweet_wed == 1
    span.wed.mr-2 = t('.wed')
  - if task.tweet_thu == 1
    span.thu.mr-2 = t('.thu')
  - if task.tweet_fri == 1
    span.fri.mr-2 = t('.fri')
  - if task.tweet_sat == 1
    span.sat.mr-2 = t('.sat')

div id="js-repeatTweetTime-#{task.id}" class='ml-3 d-inline-block'
  = task.repeat_tweet_time.strftime('%H:%M')

app/views/tasks/_task.html.slim
div id="js-task-#{task.id}" class='task-wrapper mb-1'
  div id="js-task-flash-#{task.id}" class='mb-2' style='height: 30px'
  .task-border.border-bottom.border-secondary.pb-2
    div id="js-taskTitle-#{task.id}" class='mt-2'
      = task.title

    div id="js-tweetTiming-#{task.id}" class='mt-2'
      - if task.repeat?
        div id="js-repeatTiming-#{task.id}"
          = render 'tasks/repeat_timing', task: task

    - if task.todo? && task.active?
      div id="js-nextTweetDatetime-#{task.id}" class='mt-2'
        = render 'tasks/next_tweet_datetime', task: task

    div id='js-finish-task-#{task.id}' class='d-inline-block mt-2'
      = render 'tasks/finish_btn', task: task

    div id="js-more-info-#{task.id}" class='mt-3'
      = render 'tasks/more_info_task', task: task

app/views/tasks/create.js.slim
- if @task.errors.blank?
  | $("#js-newTaskModal").modal("hide");
  | $("#js-newTaskModal").children().remove();
  | $("#js-taskList").append("
  = j(render('task', task: @task))
  | ");
  | $("#js-flash-message").children().remove();
  | $("#js-flash-message").append("
  = j(render('shared/flash_message'))
  | ");
- else
  | $('#js-errorMessage').html("
  = j(render('shared/error_message', errors: @task.errors.full_messages))
  | ");

|  setTimeout(function() {
|    $('.time-out').fadeOut('slow');
|  }, 2500);

app/views/tasks/destroy.js.slim
- if @task.errors.blank?
  | $(".top-fixed-flash-message").children().remove();
  | $(".top-fixed-flash-message").append("
  = j(render('shared/flash_message'))
  | ");
  | $("#js-task-#{@task.id}").remove();
- else
  | $('#js-task-flash-#{@task.id}').html("
  = j(render('shared/error_message', errors: @task.errors.full_messages))
  | ");

|  setTimeout(function() {
|    $('.time-out').fadeOut('slow');
|  }, 2500);

app/views/tasks/done.js.slim
- if @task.errors.blank?
  | $("#js-taskCrudList-#{@task.id}").children().remove();
  | $("#js-nextTweetDatetime-#{@task.id}").children().remove();
  | $("#js-finish-task-#{@task.id}").children().remove();
  | $("#js-task-flash-#{@task.id}").children().remove();

  | $("#js-taskCrudList-#{@task.id}").append("
  = j(render('crud_menus', task: @task))
  | ");
  | $("#js-task-flash-#{@task.id}").append("
  = j(render('shared/flash_message'))
  | ");
  | $("#js-finish-task-#{@task.id}").append("
  = j(render('tasks/finish_btn', task: @task))
  | ");
- else
  | $('#js-task-flash-#{@task.id}').html("
  = j(render('shared/error_message', errors: @task.errors.full_messages))
  | ");

|  setTimeout(function() {
|    $('.time-out').fadeOut('slow');
|  }, 2500);

app/views/tasks/finish.js.slim
- if @task.errors.blank?
  | $("#js-taskCrudList-#{@task.id}").children().remove();
  | $("#js-nextTweetDatetime-#{@task.id}").children().remove();
  | $("#js-finish-task-#{@task.id}").children().remove();
  | $("#js-task-flash-#{@task.id}").children().remove();

  | $("#js-taskCrudList-#{@task.id}").append("
  = j(render('crud_menus', task: @task))
  | ");
  | $("#js-task-flash-#{@task.id}").append("
  = j(render('shared/flash_message'))
  | ");
  | $("#js-finish-task-#{@task.id}").append("
  = j(render('tasks/finish_btn', task: @task))
  | ");
- else
  | $('#js-task-flash-#{@task.id}').html("
  = j(render('shared/error_message', errors: @task.errors.full_messages))
  | ");

|  setTimeout(function() {
|    $('.time-out').fadeOut('slow');
|  }, 2500);

app/views/tasks/pause.js.slim
- if @task.errors.blank?
  | $("#js-taskCrudList-#{@task.id}").children().remove();
  | $("#js-taskCrudList-#{@task.id}").append("
  = j(render('crud_menus', task: @task))
  | ");
  - if @task.pause?
    | $("#js-tweetTiming-#{@task.id}").children().remove();
    | $("#js-nextTweetDatetime-#{@task.id}").children().remove();
    | $("#js-task-flash-#{@task.id}").children().remove();
    | $("#js-task-flash-#{@task.id}").append("
    = j(render('shared/flash_message'))
    | ");

  - if @task.active?
    | $("#js-tweetTiming-#{@task.id}").append("
    = j(render('tasks/next_tweet_datetime', task: @task))
    | ");
    | $("#js-task-flash-#{@task.id}").children().remove();
    | $("#js-task-flash-#{@task.id}").append("
    = j(render('shared/flash_message'))
    | ");

- else
  | $('#js-task-flash-#{@task.id}').html("
  = j(render('shared/error_message', errors: @task.errors.full_messages))
  | ");

|  setTimeout(function() {
|    $('.time-out').fadeOut('slow');
|  }, 2500);

app/views/tasks/toggle_pause_flag.js.slim
- if @task.errors.blank?
  | $("#js-taskCrudList-#{@task.id}").children().remove();
  | $("#js-taskCrudList-#{@task.id}").append("
  = j(render('crud_menus', task: @task))
  | ");
  - if @task.pause?
    | $("#js-tweetTiming-#{@task.id}").children().remove();
    | $("#js-nextTweetDatetime-#{@task.id}").children().remove();
    | $("#js-task-flash-#{@task.id}").children().remove();
    | $("#js-task-flash-#{@task.id}").append("
    = j(render('shared/flash_message'))
    | ");

  - if @task.active?
    | $("#js-tweetTiming-#{@task.id}").append("
    = j(render('tasks/next_tweet_datetime', task: @task))
    | ");
    | $("#js-task-flash-#{@task.id}").children().remove();
    | $("#js-task-flash-#{@task.id}").append("
    = j(render('shared/flash_message'))
    | ");

- else
  | $('#js-task-flash-#{@task.id}').html("
  = j(render('shared/error_message', errors: @task.errors.full_messages))
  | ");

|  setTimeout(function() {
|    $('.time-out').fadeOut('slow');
|  }, 2500);